<?php

	
	/* Implements hook menu() */
	
	function user_scheme_menu() {
  
	$items['user/info'] = array(
    'title' => 'Get User Info',
    'page callback' => 'user_scheme_get_user_info',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
	);

	return $items;
}

/* Implements the callback function */

	function user_scheme_get_user_info() {

	$query = db_select('user_scheme', 'u');
	$result = $query->fields('u')
						 ->orderBy('timestamp', 'DESC')
                         ->execute()
                         ->fetchAll();
                      //  var_dump($result);
  return theme('user_scheme',array('results' => $result));

}

	/* Define template for user data page */

	function user_scheme_theme() {
		return array(
		'user_scheme' => array(
		'template' => 'user-scheme',
		'variables' => array('results' => NULL,),
			),
		);
	}
